#
# Copyright (c) Gabor Kapitany
#

---
- name: Create registry key
  become: true
  community.crypto.openssl_privatekey:
    path: /etc/docker/registry/key.pem
    owner: docker-registry
    group: docker-registry
    mode: 0600

- name: Create self signed csr
  become: true
  community.crypto.openssl_csr:
    path: /etc/docker/registry/csr.pem
    common_name: localhost
    subject_alt_name:
      - 'DNS:localhost'
      - 'DNS:registry.captaingabi.com'
    privatekey_path: /etc/docker/registry/key.pem

- name: Create self signed crt
  become: true
  community.crypto.x509_certificate:
    path: /etc/docker/registry/cert.pem
    provider: selfsigned
    csr_path: /etc/docker/registry/csr.pem
    privatekey_path: /etc/docker/registry/key.pem
  notify: restart docker-registry
