#
# Copyright (c) Gabor Kapitany
#

---
- name: Create docker-registry data folder
  become: true
  ansible.builtin.file:
    path: "{{ datadir }}/docker-registry"
    mode: 0755
    owner: "docker-registry"
    group: "docker-registry"
    state: directory

- name: Install registry mount unit
  become: true
  ansible.builtin.template:
    src: docker-registry.mount.j2
    dest: '/etc/systemd/system/var-lib-docker\x2dregistry.mount'
    mode: 0644
    owner: root
    group: root
  notify:
    - remount docker-registry data directory
    - restart docker-registry
