#
# Copyright (c) Gabor Kapitany
#

---
- name: Remount docker-registry data directory
  become: true
  ansible.builtin.systemd:
    name: var-lib-docker\x2dregistry.mount
    state: restarted

- name: Restart docker-registry
  become: true
  ansible.builtin.systemd:
    name: docker-registry
    state: restarted
